name: tests
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

env:
  AIRFLOW__CORE__ENABLE_XCOM_PICKLING: true

jobs:
  run-tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4.3.1
      - name: Installing project
        run: pip install .
      - name: Installing dev dependencies
        run: pip install -r requirements-dev.txt
      - name: Run tests
        run: make test

